const fs = require('fs');

const enNewKeys = `
  "transport.title": "Transport & Logistics",
  "transport.subtitle": "Dispatch dashboard for fleet and cargo movements.",
  "transport.action.addVehicle": "Add Vehicle",
  "transport.action.scheduleRun": "Schedule Run",
  "transport.loading": "Loading transport operations...",
  "transport.runs.title": "Upcoming Runs",
  "transport.runs.empty.title": "No scheduled runs",
  "transport.runs.empty.body": "There are no upcoming transport runs.",
  "transport.runs.today": "Today",
  "transport.runs.tomorrow": "Tomorrow",
  "transport.fleet.title": "Fleet Status",
  "transport.fleet.empty": "No vehicles registered.",
  "transport.vehicle.modal.edit": "Edit Vehicle Status",
  "transport.vehicle.modal.add": "Add Vehicle",
  "transport.vehicle.name": "Name",
  "transport.vehicle.namePlaceholder": "e.g. Truck 1",
  "transport.vehicle.licensePlate": "License Plate",
  "transport.vehicle.licensePlatePlaceholder": "e.g. AB12345",
  "transport.vehicle.type": "Type",
  "transport.vehicle.type.truck": "Truck",
  "transport.vehicle.type.van": "Van",
  "transport.vehicle.type.trailer": "Trailer",
  "transport.vehicle.type.rental": "Rental",
  "transport.vehicle.capacity": "Capacity (kg)",
  "transport.vehicle.volume": "Volume (m³)",
  "transport.vehicle.primaryDriver": "Primary Driver",
  "transport.vehicle.primaryDriver.none": "-- None --",
  "transport.vehicle.status": "Status",
  "transport.vehicle.status.available": "Available",
  "transport.vehicle.status.assigned": "Assigned",
  "transport.vehicle.status.maintenance": "Maintenance",
  "transport.vehicle.status.unavailable": "Unavailable",
  "transport.vehicle.notes": "Notes",
  "transport.vehicle.save": "Save Vehicle",
  "transport.run.modal.title": "Schedule Run",
  "transport.run.title": "Title / Description",
  "transport.run.titlePlaceholder": "e.g. Load out from venue",
  "transport.run.project": "Project",
  "transport.run.project.none": "-- Select active project --",
  "transport.run.status": "Status",
  "transport.run.status.scheduled": "Scheduled",
  "transport.run.status.in_transit": "In Transit",
  "transport.run.status.delivered": "Delivered",
  "transport.run.status.returned": "Returned / Done",
  "transport.run.vehicle": "Vehicle",
  "transport.run.vehicle.none": "-- Select vehicle --",
  "transport.run.driver": "Driver",
  "transport.run.driver.tba": "-- TBA --",
  "transport.run.origin": "Origin",
  "transport.run.originPlaceholder": "e.g. Warehouse",
  "transport.run.destination": "Destination",
  "transport.run.destinationPlaceholder": "e.g. Spektrum",
  "transport.run.departureTime": "Departure Time",
  "transport.run.loadIn": "Load In (Optional)",
  "transport.run.loadOut": "Load Out (Optional)",
  "transport.run.cargoNotes": "Cargo Notes",
  "transport.run.cargoNotesPlaceholder": "e.g. 4x Eurotruss, 2x Racks...",
  "transport.run.save": "Save Run",
  "tasks.title": "Task Management",
  "tasks.subtitle": "Cross-production control board.",
  "tasks.action.kanban": "Kanban View",
  "tasks.action.list": "List View",
  "tasks.action.create": "Global Task",
  "tasks.filter.project": "All Projects",
  "tasks.filter.department": "All Departments",
  "tasks.filter.priority": "All Priorities",
  "tasks.filter.assignee": "All Assignees",
  "tasks.filter.unassigned": "Unassigned",
  "tasks.sort.created": "Sort: Created",
  "tasks.sort.dueDate": "Sort: Due Date",
  "tasks.sort.priority": "Sort: Priority",
  "tasks.empty.title": "No tasks found",
  "tasks.empty.body": "Create a global task or check back later.",
  "tasks.empty.action": "Create Global Task",
  "tasks.column.todo": "To Do",
  "tasks.column.inProgress": "In Progress",
  "tasks.column.blocked": "Blocked",
  "tasks.column.done": "Done",
  "tasks.table.project": "Project",
  "tasks.table.task": "Task",
  "tasks.table.status": "Status",
  "tasks.table.priority": "Priority",
  "tasks.table.department": "Department",
  "tasks.table.assignee": "Assignee",
  "tasks.table.dueDate": "Due Date",
  "tasks.sidebar.title": "Task Details",
  "tasks.sidebar.project": "Project",
  "tasks.sidebar.open": "Open",
  "tasks.sidebar.taskTitle": "Title",
  "tasks.sidebar.status": "Status",
  "tasks.sidebar.priority": "Priority",
  "tasks.sidebar.department": "Department",
  "tasks.sidebar.dueDate": "Due Date",
  "tasks.sidebar.assignee": "Assignee",
  "tasks.sidebar.unassigned": "Unassigned",
  "tasks.sidebar.description": "Description & Notes",
  "tasks.sidebar.descriptionPlaceholder": "Add details, links, or notes...",
  "tasks.sidebar.created": "Created {date}",
  "tasks.sidebar.delete": "Delete Task",
  "tasks.modal.title": "Create Global Task",
  "tasks.modal.project.none": "-- Select Active Project --",
  "tasks.modal.titlePlaceholder": "What needs to be done?",
  "tasks.modal.descriptionPlaceholder": "Optional details...",
  "tasks.deleteConfirm": "Are you sure you want to delete this task?",
  "economy.overview.title": "Project Portfolio Breakdown",
  "economy.overview.table.project": "Project",
  "economy.overview.table.revenue": "Revenue",
  "economy.overview.table.expenses": "Expenses",
  "economy.overview.table.profit": "Net Profit",
  "economy.overview.table.margin": "Margin",
  "economy.overview.empty": "No projects found.",
  "economy.projects.client": "Client: {client}",
  "economy.projects.clientNone": "None",
  "economy.projects.settings": "Settings",
  "economy.projects.revenue": "Revenue",
  "economy.projects.expenses": "Expenses",
  "economy.projects.margin": "Margin",
  "economy.projects.noBudget": "No budget",
  "economy.timecards.title": "Timecards & Hours Master Queue",
  "economy.timecards.table.freelancer": "Freelancer",
  "economy.timecards.table.project": "Project",
  "economy.timecards.table.date": "Date",
  "economy.timecards.table.hours": "Hours (Net)",
  "economy.timecards.table.cost": "Cost",
  "economy.timecards.table.status": "Status",
  "economy.timecards.table.actions": "Actions",
  "economy.timecards.adj": "Adj: {adj}m",
  "economy.timecards.flag": "Flag: {reason}",
  "economy.timecards.action.approve": "Approve",
  "economy.timecards.action.reject": "Reject",
  "economy.timecards.action.flag": "Flag",
  "economy.timecards.action.adjust": "Adjust",
  "economy.timecards.action.lock": "Lock",
  "economy.timecards.readonly": "Read only",
  "economy.timecards.empty": "No timecards found.",
  "economy.expenses.title": "Direct Expenses",
  "economy.expenses.table.date": "Date",
  "economy.expenses.table.project": "Project",
  "economy.expenses.table.category": "Category",
  "economy.expenses.table.description": "Description",
  "economy.expenses.table.vendor": "Vendor / Ref",
  "economy.expenses.table.amount": "Amount",
  "economy.expenses.empty": "No expenses found.",
  "economy.recon.title": "EasyJob Reconciliation",
  "economy.recon.table.project": "Project",
  "economy.recon.table.easyjobId": "EasyJob ID",
  "economy.recon.table.internalRev": "Internal Rev",
  "economy.recon.table.easyjobRev": "EasyJob Rev",
  "economy.recon.table.difference": "Difference",
  "economy.recon.table.status": "Status",
  "economy.recon.empty": "No reconciliation data found.",
  "economy.recon.unlinked": "Unlinked",
  "economy.recon.pending": "Pending",
  "economy.recon.matched": "Matched",
  "economy.recon.mismatch": "Mismatch",
  "economy.recon.diff": "Diff: {diff}",
  "economy.modal.expense.title": "Add Expense",
  "economy.modal.expense.project": "Project",
  "economy.modal.expense.category": "Category",
  "economy.modal.expense.date": "Date",
  "economy.modal.expense.amount": "Amount",
  "economy.modal.expense.description": "Description",
  "economy.modal.expense.descriptionPlaceholder": "What was purchased?",
  "economy.modal.expense.vendor": "Vendor",
  "economy.modal.expense.vendorPlaceholder": "Optional...",
  "economy.modal.expense.reference": "Reference / Receipt",
  "economy.modal.expense.referencePlaceholder": "Optional receipt no.",
  "economy.modal.expense.save": "Save Expense",
  "economy.modal.settings.title": "Project Financial Settings",
  "economy.modal.settings.subtitle": "Set baseline revenue and budgets.",
  "economy.modal.settings.revenue": "Revenue & Contract",
  "economy.modal.settings.contractRevenue": "Contract Revenue",
  "economy.modal.settings.easyjobRevenue": "EasyJob Actual Revenue",
  "economy.modal.settings.budgets": "Department Budgets",
  "economy.modal.settings.labor": "Labor Budget",
  "economy.modal.settings.hotel": "Hotel Budget",
  "economy.modal.settings.catering": "Catering Budget",
  "economy.modal.settings.transport": "Transport Budget",
  "economy.modal.settings.subRentals": "Sub-Rentals Budget",
  "economy.modal.settings.save": "Save Settings",
  "economy.modal.timecard.title": "Timecard Action",
  "economy.modal.timecard.reason": "Reason / Note to freelancer",
  "economy.modal.timecard.reasonPlaceholder": "Explain why...",
  "economy.modal.timecard.reject": "Reject Timecard",
  "economy.modal.timecard.flag": "Flag Timecard",
  "economy.modal.adjust.title": "Adjust Timecard",
  "economy.modal.adjust.subtitle": "Producer overrides for {date}",
  "economy.modal.adjust.break": "Break Minutes (Total)",
  "economy.modal.adjust.overtime": "Overtime Minutes",
  "economy.modal.adjust.adjustment": "Adjustment Minutes",
  "economy.modal.adjust.adjustmentHelp": "+ to add paid time, - to deduct",
  "economy.modal.adjust.reason": "Reason for adjustment",
  "economy.modal.adjust.reasonPlaceholder": "Required for adjustments...",
  "economy.modal.adjust.save": "Save Adjustment",
  "economy.categories.labor": "Labor",
  "economy.categories.hotel": "Hotel",
  "economy.categories.catering": "Catering",
  "economy.categories.transport": "Transport",
  "economy.categories.subRentals": "Sub Rentals",
  "venues.title": "Venue Directory",
  "venues.subtitle": "Technical specifications and logistics for production venues.",
  "venues.action.new": "New Venue",
  "venues.searchPlaceholder": "Search venues by name or city...",
  "venues.loading": "Loading venue database...",
  "venues.empty.title": "No venues found",
  "venues.empty.body": "Your venue directory is empty. Add your first venue to get started.",
  "venues.empty.search": "No venues match your search.",
  "venues.action.add": "Add Venue",
  "venues.table.name": "Venue Name",
  "venues.table.location": "Location",
  "venues.table.techContact": "Tech Contact",
  "venues.table.contactPhone": "Contact Phone",
  "venues.table.untitled": "Untitled",
  "venues.action.back": "Back to Venues",
  "venues.discardConfirm": "Discard unsaved changes?",
  "venues.newVenue": "New Venue",
  "venues.unnamedVenue": "Unnamed Venue",
  "venues.action.save": "Save Venue",
  "venues.tab.general": "General Info",
  "venues.tab.rigging": "Rigging & Stage",
  "venues.tab.power": "Power & Cable",
  "venues.tab.logistics": "Logistics & Access",
  "venues.tab.facilities": "Facilities & Comms",
  "venues.general.venueDetails": "Venue Details",
  "venues.general.venueName": "Venue Name",
  "venues.general.address": "Address",
  "venues.general.website": "Website",
  "venues.general.techContact": "Technical Contact",
  "venues.general.contactName": "Contact Name",
  "venues.general.phoneNumber": "Phone Number",
  "venues.general.emailAddress": "Email Address",
  "venues.placeholder.enter": "Enter {field}...",
  "venues.rigging.title": "Rigging & Stage Specs",
  "venues.rigging.maxPointLoad": "Max Point Load",
  "venues.rigging.roofTrussCapacity": "Roof Truss Capacity",
  "venues.rigging.beamHeight": "Beam Height",
  "venues.rigging.stageDimensions": "Stage Dimensions",
  "venues.power.title": "Power Infrastructure",
  "venues.power.cee32A": "CEE 32A",
  "venues.power.cee63A": "CEE 63A",
  "venues.power.cee125A": "CEE 125A",
  "venues.power.panelLocations": "Panel Locations",
  "venues.power.shorePower": "Shore Power",
  "venues.logistics.title": "Logistics & Access",
  "venues.logistics.loadingDockDimensions": "Loading Dock Dimensions",
  "venues.logistics.doorClearanceHeight": "Door Clearance Height",
  "venues.logistics.rampAccess": "Ramp Access",
  "venues.logistics.freightElevatorLimits": "Freight Elevator Limits",
  "venues.logistics.truckParkingRules": "Truck Parking Rules",
  "venues.facilities.title": "Site Facilities",
  "venues.facilities.wifiCredentials": "Wi-Fi Credentials",
  "venues.facilities.productionOfficeLocations": "Production Office Locations",
  "venues.facilities.dressingRooms": "Dressing Rooms",
  "venues.deleteConfirm": "Are you sure you want to delete this venue? This action cannot be undone.",
  "clients.title": "Client Management",
  "clients.subtitle": "Central repository of all production clients and billing records.",
  "clients.action.new": "New Client",
  "clients.searchPlaceholder": "Search clients by name or org number...",
  "clients.loading": "Loading client database...",
  "clients.empty.title": "No clients found",
  "clients.empty.body": "Your client database is empty. Add your first client to get started.",
  "clients.empty.search": "No clients match your search.",
  "clients.action.add": "Add Client",
  "clients.table.companyName": "Company Name",
  "clients.table.orgNumber": "Org Number",
  "clients.table.billingTerms": "Billing Terms",
  "clients.table.contactInfo": "Contact Info",
  "clients.table.untitled": "Untitled",
  "clients.table.days": "{days} days",
  "clients.table.unnamed": "Unnamed",
  "clients.modal.clone.title": "Clone Past Project",
  "clients.modal.clone.subtitle": "This will create a new planning project using the venue, equipment, and settings from this archived event.",
  "clients.modal.clone.newName": "New Project Name",
  "clients.modal.clone.newEasyjob": "New Easyjob Number (Optional)",
  "clients.modal.clone.action": "Create Project",
  "clients.modal.clone.cloning": "Cloning...",
  "clients.action.back": "Back to Clients",
  "clients.discardConfirm": "Discard unsaved changes?",
  "clients.newClient": "New Client",
  "clients.unnamedClient": "Unnamed Client",
  "clients.orgNo": "Org No: {org}",
  "clients.action.save": "Save Client",
  "clients.tab.general": "Client Info",
  "clients.tab.projects": "Completed Productions",
  "clients.general.companyDetails": "Company Details",
  "clients.general.companyName": "Company Name",
  "clients.general.orgNumber": "Organization Number",
  "clients.general.billingAddress": "Billing Address",
  "clients.general.paymentTerms": "Default Payment Terms (Days)",
  "clients.general.contactPersonnel": "Contact Personnel",
  "clients.general.addContact": "Add Contact",
  "clients.general.contact.name": "Name",
  "clients.general.contact.role": "Role",
  "clients.general.contact.phone": "Phone",
  "clients.general.contact.email": "Email",
  "clients.general.noContacts": "No contacts added.",
  "clients.general.noContactsAvailable": "No contacts available.",
  "clients.placeholder.enter": "Enter {field}...",
  "clients.projects.title": "Production Archive",
  "clients.projects.subtitle": "Past events for this client",
  "clients.projects.empty": "No archived projects for this client yet.",
  "clients.projects.noDates": "No dates",
  "clients.projects.venue": "Venue: {venue}",
  "clients.projects.unknownVenue": "Unknown",
  "clients.projects.easyjob": "Easyjob:",
  "clients.projects.status": "Status: {status}",
  "clients.projects.action.clone": "Clone Event",
  "clients.deleteConfirm": "Are you sure you want to delete this client? This action cannot be undone.",
  "calendar.loading": "Loading calendar...",
  "calendar.status.draft": "draft",
  "calendar.status.active": "active",
  "calendar.status.confirmed": "confirmed",
  "calendar.status.completed": "completed",
  "calendar.status.archived": "archived",
  "calendar.status.canceled": "canceled"
`;

const noNewKeys = `
  "transport.title": "Transport & Logistikk",
  "transport.subtitle": "Utsendingsdashbord for bilpark og godstransport.",
  "transport.action.addVehicle": "Legg til kjøretøy",
  "transport.action.scheduleRun": "Planlegg tur",
  "transport.loading": "Laster transportoperasjoner...",
  "transport.runs.title": "Kommende Turer",
  "transport.runs.empty.title": "Ingen planlagte turer",
  "transport.runs.empty.body": "Det er ingen kommende transportturer.",
  "transport.runs.today": "I dag",
  "transport.runs.tomorrow": "I morgen",
  "transport.fleet.title": "Bilparkstatus",
  "transport.fleet.empty": "Ingen kjøretøy registrert.",
  "transport.vehicle.modal.edit": "Rediger kjøretøystatus",
  "transport.vehicle.modal.add": "Legg til kjøretøy",
  "transport.vehicle.name": "Navn",
  "transport.vehicle.namePlaceholder": "f.eks. Lastebil 1",
  "transport.vehicle.licensePlate": "Registreringsnummer",
  "transport.vehicle.licensePlatePlaceholder": "f.eks. AB12345",
  "transport.vehicle.type": "Type",
  "transport.vehicle.type.truck": "Lastebil",
  "transport.vehicle.type.van": "Varebil",
  "transport.vehicle.type.trailer": "Tilhenger",
  "transport.vehicle.type.rental": "Leiebil",
  "transport.vehicle.capacity": "Kapasitet (kg)",
  "transport.vehicle.volume": "Volum (m³)",
  "transport.vehicle.primaryDriver": "Hovedsjåfør",
  "transport.vehicle.primaryDriver.none": "-- Ingen --",
  "transport.vehicle.status": "Status",
  "transport.vehicle.status.available": "Tilgjengelig",
  "transport.vehicle.status.assigned": "Tildelt",
  "transport.vehicle.status.maintenance": "Vedlikehold",
  "transport.vehicle.status.unavailable": "Utilgjengelig",
  "transport.vehicle.notes": "Notater",
  "transport.vehicle.save": "Lagre Kjøretøy",
  "transport.run.modal.title": "Planlegg tur",
  "transport.run.title": "Tittel / Beskrivelse",
  "transport.run.titlePlaceholder": "f.eks. Utlast fra spillested",
  "transport.run.project": "Prosjekt",
  "transport.run.project.none": "-- Velg aktivt prosjekt --",
  "transport.run.status": "Status",
  "transport.run.status.scheduled": "Planlagt",
  "transport.run.status.in_transit": "Underveis",
  "transport.run.status.delivered": "Levert",
  "transport.run.status.returned": "Returnert / Ferdig",
  "transport.run.vehicle": "Kjøretøy",
  "transport.run.vehicle.none": "-- Velg kjøretøy --",
  "transport.run.driver": "Sjåfør",
  "transport.run.driver.tba": "-- TBA --",
  "transport.run.origin": "Fra",
  "transport.run.originPlaceholder": "f.eks. Lager",
  "transport.run.destination": "Til",
  "transport.run.destinationPlaceholder": "f.eks. Spektrum",
  "transport.run.departureTime": "Avreisetid",
  "transport.run.loadIn": "Innlast (Valgfritt)",
  "transport.run.loadOut": "Utlast (Valgfritt)",
  "transport.run.cargoNotes": "Laste-notater",
  "transport.run.cargoNotesPlaceholder": "f.eks. 4x Eurotruss, 2x Racks...",
  "transport.run.save": "Lagre Tur",
  "tasks.title": "Oppgavestyring",
  "tasks.subtitle": "Kontrolltavle på tvers av produksjoner.",
  "tasks.action.kanban": "Kanban-visning",
  "tasks.action.list": "Listevisning",
  "tasks.action.create": "Global Oppgave",
  "tasks.filter.project": "Alle Prosjekter",
  "tasks.filter.department": "Alle Avdelinger",
  "tasks.filter.priority": "Alle Prioriteringer",
  "tasks.filter.assignee": "Alle Tildelte",
  "tasks.filter.unassigned": "Ikke Tildelt",
  "tasks.sort.created": "Sorter: Opprettet",
  "tasks.sort.dueDate": "Sorter: Frist",
  "tasks.sort.priority": "Sorter: Prioritet",
  "tasks.empty.title": "Ingen oppgaver funnet",
  "tasks.empty.body": "Opprett en global oppgave eller sjekk tilbake senere.",
  "tasks.empty.action": "Opprett Global Oppgave",
  "tasks.column.todo": "Gjøres",
  "tasks.column.inProgress": "Pågår",
  "tasks.column.blocked": "Blokkert",
  "tasks.column.done": "Ferdig",
  "tasks.table.project": "Prosjekt",
  "tasks.table.task": "Oppgave",
  "tasks.table.status": "Status",
  "tasks.table.priority": "Prioritet",
  "tasks.table.department": "Avdeling",
  "tasks.table.assignee": "Tildelt",
  "tasks.table.dueDate": "Frist",
  "tasks.sidebar.title": "Oppgavedetaljer",
  "tasks.sidebar.project": "Prosjekt",
  "tasks.sidebar.open": "Åpne",
  "tasks.sidebar.taskTitle": "Tittel",
  "tasks.sidebar.status": "Status",
  "tasks.sidebar.priority": "Prioritet",
  "tasks.sidebar.department": "Avdeling",
  "tasks.sidebar.dueDate": "Frist",
  "tasks.sidebar.assignee": "Tildelt",
  "tasks.sidebar.unassigned": "Ikke Tildelt",
  "tasks.sidebar.description": "Beskrivelse og notater",
  "tasks.sidebar.descriptionPlaceholder": "Legg til detaljer, lenker eller notater...",
  "tasks.sidebar.created": "Opprettet {date}",
  "tasks.sidebar.delete": "Slett Oppgave",
  "tasks.modal.title": "Opprett Global Oppgave",
  "tasks.modal.project.none": "-- Velg Aktivt Prosjekt --",
  "tasks.modal.titlePlaceholder": "Hva må gjøres?",
  "tasks.modal.descriptionPlaceholder": "Valgfrie detaljer...",
  "tasks.deleteConfirm": "Er du sikker på at du vil slette denne oppgaven?",
  "economy.overview.title": "Porteføljeoversikt for prosjekter",
  "economy.overview.table.project": "Prosjekt",
  "economy.overview.table.revenue": "Inntekt",
  "economy.overview.table.expenses": "Utgifter",
  "economy.overview.table.profit": "Netto profitt",
  "economy.overview.table.margin": "Margin",
  "economy.overview.empty": "Ingen prosjekter funnet.",
  "economy.projects.client": "Kunde: {client}",
  "economy.projects.clientNone": "Ingen",
  "economy.projects.settings": "Innstillinger",
  "economy.projects.revenue": "Inntekt",
  "economy.projects.expenses": "Utgifter",
  "economy.projects.margin": "Margin",
  "economy.projects.noBudget": "Ingen budsjett",
  "economy.timecards.title": "Hovedkø for timelister",
  "economy.timecards.table.freelancer": "Frilanser",
  "economy.timecards.table.project": "Prosjekt",
  "economy.timecards.table.date": "Dato",
  "economy.timecards.table.hours": "Timer (Netto)",
  "economy.timecards.table.cost": "Kostnad",
  "economy.timecards.table.status": "Status",
  "economy.timecards.table.actions": "Handlinger",
  "economy.timecards.adj": "Juster: {adj}m",
  "economy.timecards.flag": "Flagg: {reason}",
  "economy.timecards.action.approve": "Godkjenn",
  "economy.timecards.action.reject": "Avslå",
  "economy.timecards.action.flag": "Flagg",
  "economy.timecards.action.adjust": "Juster",
  "economy.timecards.action.lock": "Lås",
  "economy.timecards.readonly": "Kun lesetilgang",
  "economy.timecards.empty": "Ingen timelister funnet.",
  "economy.expenses.title": "Direkte Utgifter",
  "economy.expenses.table.date": "Dato",
  "economy.expenses.table.project": "Prosjekt",
  "economy.expenses.table.category": "Kategori",
  "economy.expenses.table.description": "Beskrivelse",
  "economy.expenses.table.vendor": "Leverandør / Ref",
  "economy.expenses.table.amount": "Beløp",
  "economy.expenses.empty": "Ingen utgifter funnet.",
  "economy.recon.title": "EasyJob Avstemming",
  "economy.recon.table.project": "Prosjekt",
  "economy.recon.table.easyjobId": "EasyJob ID",
  "economy.recon.table.internalRev": "Intern Inntekt",
  "economy.recon.table.easyjobRev": "EasyJob Inntekt",
  "economy.recon.table.difference": "Differanse",
  "economy.recon.table.status": "Status",
  "economy.recon.empty": "Ingen avstemmingsdata funnet.",
  "economy.recon.unlinked": "Frakoblet",
  "economy.recon.pending": "Avventer",
  "economy.recon.matched": "Matchet",
  "economy.recon.mismatch": "Avvik",
  "economy.recon.diff": "Diff: {diff}",
  "economy.modal.expense.title": "Legg til Utgift",
  "economy.modal.expense.project": "Prosjekt",
  "economy.modal.expense.category": "Kategori",
  "economy.modal.expense.date": "Dato",
  "economy.modal.expense.amount": "Beløp",
  "economy.modal.expense.description": "Beskrivelse",
  "economy.modal.expense.descriptionPlaceholder": "Hva ble kjøpt?",
  "economy.modal.expense.vendor": "Leverandør",
  "economy.modal.expense.vendorPlaceholder": "Valgfritt...",
  "economy.modal.expense.reference": "Referanse / Kvittering",
  "economy.modal.expense.referencePlaceholder": "Valgfritt kvitteringsnr.",
  "economy.modal.expense.save": "Lagre Utgift",
  "economy.modal.settings.title": "Prosjektets Økonomiske Innstillinger",
  "economy.modal.settings.subtitle": "Angi basisinntekter og budsjetter.",
  "economy.modal.settings.revenue": "Inntekt & Kontrakt",
  "economy.modal.settings.contractRevenue": "Kontraktsinntekt",
  "economy.modal.settings.easyjobRevenue": "Faktisk Inntekt EasyJob",
  "economy.modal.settings.budgets": "Avdelingsbudsjetter",
  "economy.modal.settings.labor": "Lønnsbudsjett",
  "economy.modal.settings.hotel": "Hotellbudsjett",
  "economy.modal.settings.catering": "Cateringbudsjett",
  "economy.modal.settings.transport": "Transportbudsjett",
  "economy.modal.settings.subRentals": "Underleie Budsjetter",
  "economy.modal.settings.save": "Lagre Innstillinger",
  "economy.modal.timecard.title": "Timelistehandling",
  "economy.modal.timecard.reason": "Årsak / Melding til frilanser",
  "economy.modal.timecard.reasonPlaceholder": "Forklar hvorfor...",
  "economy.modal.timecard.reject": "Avslå Timeliste",
  "economy.modal.timecard.flag": "Flagg Timeliste",
  "economy.modal.adjust.title": "Juster Timeliste",
  "economy.modal.adjust.subtitle": "Produsentoverstyring for {date}",
  "economy.modal.adjust.break": "Pausetid (Totalt i minutter)",
  "economy.modal.adjust.overtime": "Overtidsminutter",
  "economy.modal.adjust.adjustment": "Justering (minutter)",
  "economy.modal.adjust.adjustmentHelp": "+ for å legge til, - for å trekke fra",
  "economy.modal.adjust.reason": "Årsak til justering",
  "economy.modal.adjust.reasonPlaceholder": "Kreves for justeringer...",
  "economy.modal.adjust.save": "Lagre Justering",
  "economy.categories.labor": "Arbeid",
  "economy.categories.hotel": "Hotell",
  "economy.categories.catering": "Catering",
  "economy.categories.transport": "Transport",
  "economy.categories.subRentals": "Underleie",
  "venues.title": "Lokasjonsoversikt",
  "venues.subtitle": "Tekniske spesifikasjoner og logistikk for produksjonslokaler.",
  "venues.action.new": "Ny Lokasjon",
  "venues.searchPlaceholder": "Søk etter lokasjoner på navn eller by...",
  "venues.loading": "Laster lokasjonsdatabase...",
  "venues.empty.title": "Ingen lokasjoner funnet",
  "venues.empty.body": "Din lokasjonsoversikt er tom. Legg til din første lokasjon for å komme i gang.",
  "venues.empty.search": "Ingen lokasjoner matcher søket ditt.",
  "venues.action.add": "Legg til Lokasjon",
  "venues.table.name": "Lokasjonsnavn",
  "venues.table.location": "Plassering",
  "venues.table.techContact": "Teknisk Kontakt",
  "venues.table.contactPhone": "Telefon",
  "venues.table.untitled": "Uten navn",
  "venues.action.back": "Tilbake til Lokasjoner",
  "venues.discardConfirm": "Forkast ulagrede endringer?",
  "venues.newVenue": "Ny Lokasjon",
  "venues.unnamedVenue": "Ikke Navngitt Lokasjon",
  "venues.action.save": "Lagre Lokasjon",
  "venues.tab.general": "Generell Info",
  "venues.tab.rigging": "Rigging & Scene",
  "venues.tab.power": "Strøm & Kabler",
  "venues.tab.logistics": "Logistikk & Tilgang",
  "venues.tab.facilities": "Fasiliteter & Kommunikasjon",
  "venues.general.venueDetails": "Lokasjonsdetaljer",
  "venues.general.venueName": "Lokasjonsnavn",
  "venues.general.address": "Adresse",
  "venues.general.website": "Nettsted",
  "venues.general.techContact": "Teknisk Kontakt",
  "venues.general.contactName": "Kontaktnavn",
  "venues.general.phoneNumber": "Telefonnummer",
  "venues.general.emailAddress": "E-postadresse",
  "venues.placeholder.enter": "Fyll inn {field}...",
  "venues.rigging.title": "Rigging & Scene Specs",
  "venues.rigging.maxPointLoad": "Maks Punktlast",
  "venues.rigging.roofTrussCapacity": "Tak Truss Kapasitet",
  "venues.rigging.beamHeight": "Bjelkehøyde",
  "venues.rigging.stageDimensions": "Scenedimensjoner",
  "venues.power.title": "Strøminfrastruktur",
  "venues.power.cee32A": "CEE 32A",
  "venues.power.cee63A": "CEE 63A",
  "venues.power.cee125A": "CEE 125A",
  "venues.power.panelLocations": "Tavleplasseringer",
  "venues.power.shorePower": "Landstrøm",
  "venues.logistics.title": "Logistikk & Tilgang",
  "venues.logistics.loadingDockDimensions": "Lasterampedimensjoner",
  "venues.logistics.doorClearanceHeight": "Dørklaring Høyde",
  "venues.logistics.rampAccess": "Rampetilgang",
  "venues.logistics.freightElevatorLimits": "Vareheisbegrensninger",
  "venues.logistics.truckParkingRules": "Regler for Lastebilparkering",
  "venues.facilities.title": "Anleggsfasiliteter",
  "venues.facilities.wifiCredentials": "Wi-Fi Innlogging",
  "venues.facilities.productionOfficeLocations": "Produksjonskontor Plassering",
  "venues.facilities.dressingRooms": "Garderober",
  "venues.deleteConfirm": "Er du sikker på at du vil slette denne lokasjonen? Dette kan ikke angres.",
  "clients.title": "Kundebehandling",
  "clients.subtitle": "Sentrale arkiv for alle produksjonskunder og faktureringsdata.",
  "clients.action.new": "Ny Kunde",
  "clients.searchPlaceholder": "Søk etter kunder på navn eller orgnummer...",
  "clients.loading": "Laster kundedatabase...",
  "clients.empty.title": "Ingen kunder funnet",
  "clients.empty.body": "Kundedatabasen er tom. Legg til din første kunde for å komme i gang.",
  "clients.empty.search": "Ingen kunder matcher søket ditt.",
  "clients.action.add": "Legg til Kunde",
  "clients.table.companyName": "Firmanavn",
  "clients.table.orgNumber": "Orgnummer",
  "clients.table.billingTerms": "Faktureringsbetingelser",
  "clients.table.contactInfo": "Kontaktinfo",
  "clients.table.untitled": "Uten navn",
  "clients.table.days": "{days} dager",
  "clients.table.unnamed": "Ikke navngitt",
  "clients.modal.clone.title": "Klon Tidligere Prosjekt",
  "clients.modal.clone.subtitle": "Dette vil opprette et nytt planleggingsprosjekt basert på lokasjon, utstyr og innstillinger fra dette arkiverte arrangementet.",
  "clients.modal.clone.newName": "Nytt Prosjektnavn",
  "clients.modal.clone.newEasyjob": "Nytt Easyjob-nummer (Valgfritt)",
  "clients.modal.clone.action": "Opprett Prosjekt",
  "clients.modal.clone.cloning": "Kloner...",
  "clients.action.back": "Tilbake til Kunder",
  "clients.discardConfirm": "Forkast ulagrede endringer?",
  "clients.newClient": "Ny Kunde",
  "clients.unnamedClient": "Ikke Navngitt Kunde",
  "clients.orgNo": "Org nr: {org}",
  "clients.action.save": "Lagre Kunde",
  "clients.tab.general": "Kundeinfo",
  "clients.tab.projects": "Tidligere Produksjoner",
  "clients.general.companyDetails": "Firmadetaljer",
  "clients.general.companyName": "Firmanavn",
  "clients.general.orgNumber": "Organisasjonsnummer",
  "clients.general.billingAddress": "Faktureringsadresse",
  "clients.general.paymentTerms": "Standard Betalingsbetingelser (Dager)",
  "clients.general.contactPersonnel": "Kontaktpersonell",
  "clients.general.addContact": "Legg til Kontakt",
  "clients.general.contact.name": "Navn",
  "clients.general.contact.role": "Rolle",
  "clients.general.contact.phone": "Telefon",
  "clients.general.contact.email": "E-post",
  "clients.general.noContacts": "Ingen kontakter lagt til.",
  "clients.general.noContactsAvailable": "Ingen kontakter tilgjengelig.",
  "clients.placeholder.enter": "Fyll inn {field}...",
  "clients.projects.title": "Produksjonsarkiv",
  "clients.projects.subtitle": "Tidligere arrangementer for denne kunden",
  "clients.projects.empty": "Ingen arkiverte prosjekter for denne kunden ennå.",
  "clients.projects.noDates": "Ingen datoer",
  "clients.projects.venue": "Lokasjon: {venue}",
  "clients.projects.unknownVenue": "Ukjent",
  "clients.projects.easyjob": "Easyjob:",
  "clients.projects.status": "Status: {status}",
  "clients.projects.action.clone": "Klon Arrangement",
  "clients.deleteConfirm": "Er du sikker på at du vil slette denne kunden? Dette kan ikke angres.",
  "calendar.loading": "Laster kalender...",
  "calendar.status.draft": "utkast",
  "calendar.status.active": "aktiv",
  "calendar.status.confirmed": "bekreftet",
  "calendar.status.completed": "fullført",
  "calendar.status.archived": "arkivert",
  "calendar.status.canceled": "kansellert"
`;

function inject(filePath, newKeys) {
  let content = fs.readFileSync(filePath, 'utf8');
  let parts = content.split('// ---------- Settings ----------');
  content = parts[0] + '// ---------- Settings ----------\n' + newKeys + '\n' + parts[1];
  fs.writeFileSync(filePath, content);
}

inject('artifacts/rigging-load-report/src/lib/i18n/translations/en.ts', enNewKeys);
inject('artifacts/rigging-load-report/src/lib/i18n/translations/no.ts', noNewKeys);
