// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/itinerary-day/Dark.tsx": () => import("../components/mockups/itinerary-day/Dark.tsx"),
  "./components/mockups/itinerary-day/Light.tsx": () => import("../components/mockups/itinerary-day/Light.tsx"),
  "./components/mockups/ehs-redesign/FreelancePortal.tsx": () => import("../components/mockups/ehs-redesign/FreelancePortal.tsx"),
  "./components/mockups/ehs-redesign/Linear.tsx": () => import("../components/mockups/ehs-redesign/Linear.tsx"),
  "./components/mockups/ehs-redesign/Stripe.tsx": () => import("../components/mockups/ehs-redesign/Stripe.tsx"),
  "./components/mockups/ehs-redesign/Vercel.tsx": () => import("../components/mockups/ehs-redesign/Vercel.tsx")
};
